### ISSUE TITLE
2 Questions Regarding the Implementation of apkfile

### ISSUE THREAD

**Issue by benldrmn** [CalebFenton/apkfile#3]
Hi,

First of all, thank you for your wonderful work.
I have 2 questions:

1. Is apkfile thread-safe? that is, analyzing different apks simultaneously with different threads may present problems? reading the code, I couldn't find a reason that it wouldn't. It doesn't seem to rely on shared data structures, for example, while analyzing an apk.

2. I noticed that the collections used to hold the extracted features (for example, the app's activities) are of type LinkedList. What are your thoughts about using ArrayLists for better performance? Arrays are much more cache-friendly than LinkedList, and though admittedly I haven't tried it, I think this minor change might improve performance.

Thanks!
Ben

**Comment by CalebFenton** [comment]
Sorry for the slow reply. Apparently, I wasn't configured to "watch" this repo and didn't get notified.

1. Yeah, it should be thread safe. I really only ever use it in a multi-threaded, daemon mode, and I designed it with threads in mind. There's very little shared state (possibly none)
2. I use LinkedLists when I want to minimize list size and list elements don't need to be randomly accessible. If you see a place using LinkedList, but items are frequently accessed by index (other than 0), feel free to submit a PR. I only use ArrayLists when I need fast random access, but most of the time I just need a list of things that I can append to and then eventually sequentially iterate.

Going to close this, but feel free to continue the conversations. I'm watching this project now.

**Comment by benldrmn** [comment]
Hi, that's alright.

Regarding LinkedLists vs ArrayLists, ArraysLists not only shine when random access to the data structure is needed, but also when iterating over it sequentially, as the data is saved sequentially in the memory (as opposed to LinkedList where it's scattered all over), and thus the iteration is so much faster due to less cache misses. Every time you access read an entry in the array, you read a whole cache line from the RAM which has other entries in it as well (as they are close-by to the entry you just read due to the nature of an array and how the data is stored in memory) and thus you have the next array entries already in cache which is ridiculously faster than RAM. So iterating ArraysList sequentially is much more cache-friendly than iterating LinkedLists where every iteration would probably cause a cache-miss.

What are you thoughts about that?

**Comment by CalebFenton** [comment]
Can you point to some benchmarks showing sequential access is faster for ArrayLists? I did some quick poking around and it seems like there's a lot of debate over when to prefer Linked vs Array. I think the only way to know for sure would be to benchmark and profile similar code or apkfile itself.

I'm curious and would be open to changing it if I knew it was better. Should be possible to benchmark against a large sample set to establish baseline. Then, replace everything with ArrayList, run same set again and compare speed and memory performance. Want to give it a shot?

**Comment by benldrmn** [comment]
I agree that when talking performence, you got to measure things. I'm quite busy at the time but I will try to find some time to benchmark it.
