### ISSUE TITLE
build error help

### ISSUE THREAD

**Issue by def-ra** [CalebFenton/apkfile#4]
Hi Caleb,

Im getting the follow errors when running:

test@test-VirtualBox:~/Downloads/apkfile$ ./gradlew build
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
:compileJava
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:19: warning: RDN is internal proprietary API and may be removed in a future release
import sun.security.x509.RDN;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:20: warning: X500Name is internal proprietary API and may be removed in a future release
import sun.security.x509.X500Name;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:19: warning: RDN is internal proprietary API and may be removed in a future release
import sun.security.x509.RDN;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:20: warning: X500Name is internal proprietary API and may be removed in a future release
import sun.security.x509.X500Name;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:19: warning: RDN is internal proprietary API and may be removed in a future release
import sun.security.x509.RDN;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:20: warning: X500Name is internal proprietary API and may be removed in a future release
import sun.security.x509.X500Name;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:19: warning: RDN is internal proprietary API and may be removed in a future release
import sun.security.x509.RDN;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:20: warning: X500Name is internal proprietary API and may be removed in a future release
import sun.security.x509.X500Name;
                        ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/utils/Utils.java:40: warning: [unchecked] unchecked call to adjustOrPutValue(K,int,int) as a member of the raw type TObjectIntMap
            dest.adjustOrPutValue(key, value, value);
                                 ^
  where K is a type-variable:
    K extends Object declared in interface TObjectIntMap
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/utils/Utils.java:47: warning: [unchecked] unchecked call to adjustOrPutValue(K,long,long) as a member of the raw type TObjectLongMap
            dest.adjustOrPutValue(key, value, value);
                                 ^
  where K is a type-variable:
    K extends Object declared in interface TObjectLongMap
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:37: warning: [unchecked] unchecked call to getMatches(Selector<T>) as a member of the raw type Store
        Collection<X509CertificateHolder> matches = data.getCertificates().getMatches(null);
                                                                                     ^
  where T is a type-variable:
    T extends Object declared in interface Store
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:37: warning: [unchecked] unchecked conversion
        Collection<X509CertificateHolder> matches = data.getCertificates().getMatches(null);
                                                                                     ^
  required: Collection<X509CertificateHolder>
  found:    Collection
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:39: error: incompatible types: org.bouncycastle.asn1.x500.X500Name cannot be converted to sun.security.x509.X500Name
            allRdns.add(buildRdns(holder.getSubject(), holder.getIssuer()));
                                                   ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:45: warning: X500Name is internal proprietary API and may be removed in a future release
    private static SubjectAndIssuerRdns buildRdns(X500Name subject, X500Name issuer) {
                                                  ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:45: warning: X500Name is internal proprietary API and may be removed in a future release
    private static SubjectAndIssuerRdns buildRdns(X500Name subject, X500Name issuer) {
                                                                    ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:56: error: cannot find symbol
        for (RDN rdn : subject.getRDNs()) {
                              ^
  symbol:   method getRDNs()
  location: variable subject of type X500Name
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:56: warning: RDN is internal proprietary API and may be removed in a future release
        for (RDN rdn : subject.getRDNs()) {
             ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:57: error: cannot find symbol
            for (AttributeTypeAndValue typeAndValue : rdn.getTypesAndValues()) {
                                                         ^
  symbol:   method getTypesAndValues()
  location: variable rdn of type RDN
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:65: error: cannot find symbol
        for (RDN rdn : subject.getRDNs()) {
                              ^
  symbol:   method getRDNs()
  location: variable subject of type X500Name
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:65: warning: RDN is internal proprietary API and may be removed in a future release
        for (RDN rdn : subject.getRDNs()) {
             ^
/home/test/Downloads/apkfile/src/main/java/org/cf/apkfile/apk/Certificate.java:66: error: cannot find symbol
            for (AttributeTypeAndValue typeAndValue : rdn.getTypesAndValues()) {
                                                         ^
  symbol:   method getTypesAndValues()
  location: variable rdn of type RDN
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
5 errors
16 warnings
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.626 secs

**Comment by CalebFenton** [comment]
What's the output of `java -version` ?
