### ISSUE TITLE
where is AutoValue_LibraryChunk_Entry in LibraryChunk.java

### ISSUE THREAD

**Issue by hexufeng** [CalebFenton/apkfile#9]
IDEA can not recogonize "AutoValue_LibraryChunk_Entry" in class LibraryChunk, and also i did not found it imported, what's it ?

**Comment by hexufeng** [comment]
i found it , in Google AutoValue ..

**Comment by CalebFenton** [comment]
It was quite confusing for me when I first saw it too. Glad you got it sorted.
